version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions-minor:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      docusaurus:
        patterns:
          - "@docusaurus*"
      npm-development:
        dependency-type: development
        update-types:
          - minor
          - patch
        exclude-patterns:
          - "@docusaurus*"
      npm-production:
        dependency-type: production
        update-types:
          - patch
        exclude-patterns:
          - "@docusaurus*"
